In [1]:
import pandas as pd
import re

In [6]:
columns = ['sentiment','id','date','flag','user','text']

In [7]:
df = pd.read_csv('training.1600000.processed.noemoticon.csv', encoding='latin-1',names = columns)

In [8]:
df['sentiment'] = df['sentiment'].map({0: 'Negative', 4: 'Positive'})
df

,sentiment,id,date,flag,user,text
0,Negative,1467810369,Mon Apr 06 22:19:45 PDT 2009,NO_QUERY,_TheSpecialOne_,"@switchfoot http://twitpic.com/2y1zl - Awww, t..."
1,Negative,1467810672,Mon Apr 06 22:19:49 PDT 2009,NO_QUERY,scotthamilton,is upset that he can't update his Facebook by ...
2,Negative,1467810917,Mon Apr 06 22:19:53 PDT 2009,NO_QUERY,mattycus,@Kenichan I dived many times for the ball. Man...
3,Negative,1467811184,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,ElleCTF,my whole body feels itchy and like its on fire
4,Negative,1467811193,Mon Apr 06 22:19:57 PDT 2009,NO_QUERY,Karoli,"@nationwideclass no, it's not behaving at all...."
...,...,...,...,...,...,...
1599995,Positive,2193601966,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,AmandaMarie1028,Just woke up. Having no school is the best fee...
1599996,Positive,2193601969,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,TheWDBoards,TheWDB.com - Very cool to hear old Walt interv...
1599997,Positive,2193601991,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,bpbabe,Are you ready for your MoJo Makeover? Ask me f...
1599998,Positive,2193602064,Tue Jun 16 08:40:49 PDT 2009,NO_QUERY,tinydiamondz,Happy 38th Birthday to my boo of alll time!!! ...
1599999,Positive,2193602129,Tue Jun 16 08:40:50 PDT 2009,NO_QUERY,RyanTrevMorris,happy #charitytuesday @theNSPCC @SparksCharity...

In [27]:
stop_words = []

In [9]:
word_dict_negative = {}
word_dict_positive = {}

for text_row in range(len(df['text'])) :
    list_of_words = re.sub(r'[^\w\s]', '', df['text'][text_row]).split()
    list_of_words_2 = []
    for word in list_of_words :
        word = word.lower()
        word = word.replace('?','')
        word = word.replace('!','')
        word = word.replace('.','')
        word = word.replace('"','')
        word = word.replace("'",'')
        word = word.replace('#','')
        word = word.replace('$','')
        word = word.replace(':','')
        
        if '@' not in word and 'http' not in word :
            list_of_words_2.append(word)
            
    for word in list_of_words_2 :
        if df['sentiment'][text_row] == 'Negative' :
            word_dict_negative[word] = word_dict_negative.get(word,0) + 1
        else :
            word_dict_positive[word] = word_dict_positive.get(word,0) + 1

In [10]:
word_dict_negative

{'switchfoot': 12,
 'awww': 3220,
 'thats': 13027,
 'a': 180646,
 'bummer': 1316,
 'you': 94065,
 'shoulda': 263,
 'got': 32983,
 'david': 1052,
 'carr': 26,
 'of': 92558,
 'third': 444,
 'day': 38000,
 'to': 312592,
 'do': 35119,
 'it': 118975,
 'd': 2591,
 'is': 127604,
 'upset': 2456,
 'that': 72585,
 'he': 16014,
 'cant': 43591,
 'update': 2444,
 'his': 8322,
 'facebook': 1930,
 'by': 12698,
 'texting': 356,
 'and': 151147,
 'might': 4675,
 'cry': 3811,
 'as': 18303,
 'result': 298,
 'school': 12369,
 'today': 36190,
 'also': 4650,
 'blah': 1128,
 'kenichan': 7,
 'i': 462019,
 'dived': 3,
 'many': 4675,
 'times': 3810,
 'for': 98679,
 'the': 256201,
 'ball': 676,
 'managed': 523,
 'save': 1256,
 '50': 667,
 'rest': 2524,
 'go': 45126,
 'out': 42992,
 'bounds': 10,
 'my': 189062,
 'whole': 3436,
 'body': 1646,
 'feels': 3428,
 'itchy': 402,
 'like': 40640,
 'its': 58544,
 'on': 83563,
 'fire': 742,
 'nationwideclass': 1,
 'no': 52099,
 'not': 73509,
 'behaving': 36,
 'at': 62073,
 'all': 41029,
 'im': 102625,
 'mad': 2798,
 'why': 20344,
 'am': 28234,
 'here': 18912,
 'because': 8551,
 'see': 20373,
 'over': 13686,
 'there': 19981,
 'kwesidei': 1,
 'crew': 283,
 'need': 22045,
 'hug': 1318,
 'loltrish': 1,
 'hey': 4878,
 'long': 9296,
 'time': 26771,
 'yes': 5610,
 'rains': 375,
 'bit': 5436,
 'only': 17328,
 'lol': 21676,
 'fine': 1527,
 'thanks': 5617,
 'hows': 718,
 'tatiana_k': 6,
 'nope': 1550,
 'they': 20858,
 'didnt': 19955,
 'have': 82465,
 'twittera': 5,
 'que': 300,
 'me': 90173,
 'muera': 1,
 'spring': 480,
 'break': 2489,
 'in': 114308,
 'plain': 222,
 'city': 1655,
 'snowing': 112,
 'just': 63177,
 'repierced': 9,
 'ears': 499,
 'caregiving': 1,
 'couldnt': 4861,
 'bear': 430,
 'watch': 7383,
 'thought': 5967,
 'ua': 11,
 'loss': 827,
 'was': 58993,
 'embarrassing': 124,
 'octolinz16': 1,
 'counts': 73,
 'idk': 1714,
 'did': 13041,
 'either': 3439,
 'never': 11085,
 'talk': 4426,
 'anymore': 5441,
 'smarrison': 1,
 'wouldve': 433,
 'been': 20121,
 'first': 6944,
 'but': 81261,
 'gun': 139,
 'really': 31221,
 'though': 14489,
 'zac': 80,
 'snyders': 1,
 'doucheclown': 1,
 'iamjazzyfizzle': 1,
 'wish': 21983,
 'with': 49923,
 'miss': 30500,
 'iamlilnicki': 1,
 'how': 19750,
 'premiere': 180,
 'hollis': 2,
 'death': 1225,
 'scene': 292,
 'will': 22711,
 'hurt': 4365,
 'severely': 59,
 'film': 728,
 'wry': 6,
 'directors': 15,
 'cut': 2365,
 'now': 50629,
 'about': 26042,
 'file': 359,
 'taxes': 92,
 'lettya': 3,
 'ahh': 1558,
 'ive': 13259,
 'always': 6545,
 'wanted': 5292,
 'rent': 301,
 'love': 16624,
 'soundtrack': 85,
 'fakerpattypattz': 1,
 'oh': 21523,
 'dear': 1824,
 'were': 12408,
 'drinking': 1170,
 'forgotten': 323,
 'table': 413,
 'drinks': 417,
 'alydesigns': 1,
 'most': 3497,
 'so': 86747,
 'get': 45316,
 'much': 19768,
 'done': 6678,
 'one': 26362,
 'friend': 4819,
 'called': 2296,
 'asked': 894,
 'meet': 1942,
 'her': 17313,
 'mid': 177,
 'valley': 139,
 'todaybut': 62,
 'sigh': 2730,
 'angry_barista': 1,
 'baked': 137,
 'cake': 932,
 'ated': 3,
 'this': 52086,
 'week': 11750,
 'going': 33440,
 'had': 27568,
 'hoped': 207,
 'blagh': 7,
 'class': 3560,
 '8': 2487,
 'tomorrow': 18451,
 'hate': 17038,
 'when': 22033,
 'call': 4261,
 'wake': 2639,
 'people': 9985,
 'up': 48380,
 'myself': 5012,
 'sleep': 17775,
 'after': 9830,
 'watching': 8307,
 'marley': 230,
 'sad': 27143,
 'misslilly': 1,
 'ooooh': 141,
 'leslie': 34,
 'ok': 6843,
 'wont': 11890,
 'again': 17519,
 'meh': 496,
 'almost': 4178,
 'lover': 138,
 'exception': 44,
 'track': 500,
 'gets': 2460,
 'depressed': 1242,
 'every': 3255,
 'some1': 163,
 'hacked': 264,
 'account': 1446,
 'aim': 384,
 'make': 12163,
 'new': 15353,
 'alielayus': 1,
 'want': 29732,
 'promote': 48,
 'gear': 237,
 'groove': 32,
 'unfornately': 2,
 'ride': 1524,
 'may': 3837,
 'b': 2759,
 'anaheim': 34,
 'sleeping': 2382,
 'an': 17497,
 'option': 404,
 'realizing': 154,
 'evaluations': 6,
 'morning': 13151,
 'work': 44057,
 'afternoon': 1577,
 'julieebaby': 2,
 'awe': 457,
 'too': 36627,
 '1': 5271,
 'humpninja': 1,
 'asian': 190,
 'eyes': 2160,
 'night': 19010,
 'sick': 14173,
 'spent': 1529,
 'hour': 4671,
 'sitting': 2996,
 'shower': 1584,
 'cause': 4418,
 'stand': 794,
 'held': 176,
 'back': 32516,
 'puke': 161,
 'champ': 33,
 'bed': 11843,
 'cocomix04': 1,
 'ill': 14041,
 'tell': 4337,
 'ya': 3130,
 'story': 1314,
 'later': 3679,
 'good': 28552,
 'be': 58389,
 'workin': 604,
 'three': 1605,
 'more': 18641,
 'hours': 8348,
 'missxu': 4,
 'sorry': 20315,
 'came': 3184,
 'gmt1': 2,
 'fleurylis': 2,
 'dont': 44913,
 'depressing': 1137,
 'think': 21697,
 'even': 12167,
 'know': 25919,
 'kids': 2840,
 'suitcases': 15,
 '812': 11,
 '123': 27,
 'gym': 1675,
 '35': 322,
 'or': 14736,
 '6': 2900,
 'then': 14770,
 '610': 18,
 'another': 8093,
 'gonna': 13012,
 'fly': 812,
 'girlfriend': 430,
 'feel': 21804,
 'getting': 13406,
 'study': 2808,
 'tomorrows': 356,
 'practical': 61,
 'exam': 3870,
 'hes': 4736,
 'reason': 2006,
 'teardrops': 15,
 'guitar': 798,
 'who': 7195,
 'has': 20948,
 'enough': 3864,
 'heart': 2786,
 'feeling': 10872,
 'wanna': 11809,
 'still': 28758,
 'jonathanrknight': 418,
 'soo': 2938,
 'finally': 3981,
 'comfortable': 140,
 'missed': 8405,
 'falling': 850,
 'asleep': 2990,
 'heard': 2556,
 'tracy': 42,
 'girls': 2074,
 'being': 9980,
 'found': 4518,
 'breaks': 416,
 'family': 3401,
 'viennah': 1,
 'yay': 2988,
 'happy': 6275,
 'your': 20755,
 'job': 4336,
 'means': 2024,
 'less': 1705,
 'checked': 738,
 'user': 208,
 'timeline': 93,
 'blackberry': 988,
 'looks': 5293,
 'twanking': 1,
 'happening': 878,
 'are': 33878,
 'ppl': 1765,
 'having': 8779,
 'probs': 280,
 'w': 2870,
 'bgs': 13,
 'uids': 1,
 'manwas': 1,
 'ironing': 194,
 'jeancjumbes': 1,
 'fave': 342,
 'top': 1481,
 'wear': 1335,
 'meeting': 1576,
 'burnt': 1205,
 'strangely': 49,
 'lilo': 10,
 'samro': 1,
 'breaking': 712,
 'tea': 1393,
 'before': 7138,
 'retweeting': 50,
 'broadband': 138,
 'plan': 1147,
 'massive': 592,
 'broken': 2675,
 'promise': 460,
 'via': 1156,
 'wwwdiigocomtautao': 1,
 'waiting': 5263,
 'we': 23586,
 'localtweeps': 3,
 'wow': 4266,
 'tons': 376,
 'replies': 448,
 'from': 27945,
 'unfollow': 200,
 'can': 20094,
 'friends': 6853,
 'tweets': 2665,
 'youre': 6173,
 'scrolling': 37,
 'feed': 560,
 'lot': 4215,
 'our': 7058,
 'duck': 160,
 'chicken': 983,
 'taking': 3111,
 'wayyy': 108,
 'hatch': 20,
 'put': 4185,
 'vacation': 1448,
 'photos': 889,
 'online': 2391,
 'few': 4343,
 'yrs': 386,
 'ago': 3111,
 'pc': 1038,
 'crashed': 681,
 'forget': 1175,
 'name': 1903,
 'site': 1741,
 'andywana': 1,
 'sure': 5572,
 'what': 25672,
 'pos': 40,
 'trade': 180,
 'away': 8299,
 'company': 874,
 'assets': 18,
 'andy': 276,
 'oanhlove': 4,
 'happens': 1141,
 'dallas': 443,
 'show': 7552,
 'gotta': 5106,
 'say': 6828,
 'youd': 415,
 'shows': 1383,
 'would': 13577,
 'use': 3709,
 'music': 2895,
 'game': 4660,
 'mmm': 394,
 'ugh92': 1,
 'degrees': 638,
 'where': 7972,
 'u': 22615,
 'move': 2249,
 'already': 9178,
 'sd': 181,
 'hmmm': 861,
 'random': 689,
 'glad': 2239,
 'hear': 5404,
 'yer': 139,
 'doing': 7665,
 'well': 19880,
 'batmanyng': 1,
 'ps3': 317,
 'commission': 50,
 'wutcha': 1,
 'playing': 3156,
 'copped': 13,
 'blood': 999,
 'sand': 162,
 'leaving': 3911,
 'parking': 381,
 'life': 7276,
 'cool': 3824,
 'sadly': 2184,
 'gotten': 846,
 'experience': 514,
 'post': 1998,
 'coitus': 1,
 'cigarette': 81,
 'such': 4585,
 'nice': 6433,
 'bad': 21347,
 'rain': 7832,
 'comes': 1714,
 '5am': 471,
 'starrbby': 5,
 'around': 4341,
 'lost': 9382,
 'pay': 1607,
 'phone': 9095,
 'bill': 628,
 'lmao': 1676,
 'aw': 2700,
 'shucks': 98,
 'damm': 96,
 'mo': 421,
 'jobs': 504,
 'money': 3951,
 'hell': 3659,
 'min': 869,
 'wage': 27,
 '4': 8410,
 'fn': 63,
 'clams': 6,
 'katortiz': 2,
 'forever': 1457,
 'soon': 8245,
 'lt_algonquin': 4,
 'agreed': 278,
 'saw': 4533,
 'failwhale': 10,
 'allllll': 53,
 'jdarter': 1,
 'haha': 9537,
 'dude': 1982,
 'look': 5042,
 'em': 1074,
 'unless': 657,
 'someone': 7087,
 'says': 3210,
 'added': 288,
 'terrible': 1626,
 'pop': 464,
 'ninjen': 4,
 'right': 14817,
 'start': 5128,
 'working': 10632,
 'nikster': 1,
 'jared': 79,
 'least': 4186,
 'diss': 29,
 'bands': 248,
 'trace': 84,
 'clearly': 267,
 'ugly': 753,
 'attire': 8,
 'puma': 17,
 'singlet': 4,
 'adidas': 16,
 'shortsand': 1,
 'black': 1355,
 'business': 866,
 'socks': 202,
 'leather': 97,
 'shoes': 1083,
 'lucky': 2141,
 'run': 2605,
 'into': 6023,
 'any': 8993,
 'cute': 1752,
 'location': 191,
 'picnic': 213,
 'smells': 413,
 'citrus': 9,
 'ashleyac': 2,
 'donkey': 56,
 'sensitive': 100,
 'comments': 413,
 'nevertheless': 32,
 'hed': 205,
 'med': 95,
 'mug': 110,
 'asap': 498,
 'charger': 495,
 'awol': 24,
 'csi': 114,
 'tonight': 12771,
 'fml': 1560,
 'arms': 502,
 'sore': 3309,
 'tennis': 417,
 'wonders': 275,
 'unhappy': 306,
 'split': 261,
 'seccond': 1,
 'saying': 1595,
 'bye': 2126,
 'statravelau': 1,
 'ur': 4893,
 'newsletter': 39,
 'those': 4540,
 'fares': 13,
 'unbelievable': 97,
 'shame': 2053,
 'booked': 318,
 'paid': 770,
 'mine': 3647,
 'missin': 633,
 'boo': 4016,
 'markhardy1974': 2,
 'itm': 7,
 'damn': 8871,
 'chalk': 25,
 'chalkboard': 5,
 'useless': 292,
 'blast': 392,
 'getty': 10,
 'villa': 28,
 'hates': 1872,
 'shes': 3757,
 'throat': 2738,
 'worse': 2245,
 'msdrama': 2,
 'sup': 83,
 'mama': 447,
 'tummy': 2018,
 'hurts': 7058,
 'wonder': 1392,
 'if': 18696,
 'hypnosis': 5,
 'anything': 4929,
 'stop': 4785,
 'smoking': 254,
 'fat': 1064,
 'ones': 1946,
 'januarycrimson': 5,
 'babe': 914,
 'fam': 598,
 'annoys': 70,
 'thankfully': 131,
 'theyre': 2842,
 'muahaha': 12,
 'evil': 576,
 'laugh': 533,
 'hollywoodheat': 2,
 'should': 9125,
 'attention': 380,
 'covered': 337,
 'photoshop': 222,
 'webpage': 29,
 'design': 418,
 'undergrad': 16,
 'wednesday': 1039,
 'bday': 1412,
 '2': 21870,
 'poor': 7210,
 'cameron': 45,
 'hills': 764,
 'pray': 911,
 'please': 7760,
 'ex': 404,
 'threatening': 38,
 'sh': 42,
 'myour': 1,
 'babies': 484,
 '1st': 1378,
 'birthday': 2625,
 'party': 4051,
 'jerk': 256,
 'headache': 5140,
 'makeherfamous': 1,
 'hmm': 1259,
 'enjoy': 1606,
 'him': 11178,
 'problems': 1144,
 'constants': 2,
 'things': 5708,
 'find': 9255,
 'ulike': 2,
 'strider': 1,
 'little': 8309,
 'puppy': 977,
 'ryleegracewana': 1,
 'steves': 13,
 'since': 5809,
 'easter': 176,
 'wnt': 116,
 'able': 3865,
 'ohh': 895,
 'actually': 4447,
 'won': 1409,
 'bracket': 20,
 'pools': 42,
 'wasnt': 4644,
 'stark': 6,
 'follow': 2451,
 'nite': 1429,
 'favorite': 1276,
 'teams': 137,
 'astros': 22,
 'spartans': 11,
 'lose': 1410,
 'tw': 30,
 'missing': 7097,
 'northern': 87,
 'calif': 8,
 'girl': 4172,
 'police': 289,
 'remains': 66,
 'california': 448,
 'mangaaa': 1,
 'hope': 14369,
 'increase': 75,
 'capacity': 53,
 'fast': 1782,
 'yesterday': 5166,
 'pain': 3697,
 'fail': 3016,
 'whale': 129,
 '15': 1244,
 'behind': 1180,
 'classes': 907,
 'quothousequot': 10,
 'kpreyes': 1,
 'remember': 2223,
 'bum': 304,
 'leg': 997,
 'strikes': 89,
 'serious': 1039,
 'paradisej': 1,
 'their': 4383,
 'kinds': 151,
 'complaints': 27,
 'laptop': 2455,
 'overheating': 30,
 'recalls': 4,
 'emily': 163,
 'mommy': 770,
 'training': 764,
 'she': 13082,
 'misses': 1090,
 'rather': 1517,
 'send': 2121,
 'messages': 702,
 'than': 6958,
 '3rd': 648,
 'mixed': 221,
 'sophmore': 10,
 'year': 6155,
 'henkuyinepu': 2,
 'overrated': 53,
 'marykatherine_q': 1,
 'wondered': 74,
 'same': 5944,
 'thing': 7586,
 'moscow': 33,
 'laying': 803,
 'voice': 1267,
 'sooo': 3653,
 'killed': 1041,
 'off': 18920,
 'kutner': 26,
 'house': 6958,
 'whyyyyyyyy': 12,
 'jacobsummers': 2,
 'them': 12434,
 'mea': 13,
 'culpa': 5,
 'alliana07': 2,
 'sense': 479,
 'suicide': 148,
 'refuse': 159,
 'believe': 4677,
 'happened': 2937,
 'salancaster': 1,
 'mercedesashley': 2,
 'grind': 165,
 'inspirational': 23,
 'saddening': 36,
 'cuz': 3286,
 'hibanick': 4,
 'yeah': 9220,
 'wudnt': 27,
 'chance': 1493,
 'ugh': 8299,
 '130am': 27,
 'hanging': 862,
 'crooners': 3,
 'sing': 646,
 'sucks': 9668,
 'erre_sc': 1,
 'aaw': 50,
 'bh': 28,
 'quotmorningquot': 3,
 'aww': 5073,
 'beach': 2669,
 'pissed': 1408,
 'theres': 4329,
 'asbas': 1,
 'radio': 930,
 'station': 632,
 'n': 5426,
 'flipped': 43,
 'upside': 152,
 'down': 11549,
 'head': 5376,
 'some': 18888,
 'ramen': 81,
 'sounds': 2706,
 'sides': 86,
 'mention': 476,
 'crying': 2023,
 'made': 5879,
 'late': 5607,
 'snack': 154,
 'glass': 510,
 'oj': 63,
 'bc': 1420,
 'quotdown': 4,
 'sicknessquot': 3,
 'sleepugh': 4,
 'allyheman': 3,
 'big': 5128,
 'fan': 1373,
 'camilla': 28,
 'belle': 58,
 'grum': 14,
 'wah': 310,
 'clip': 143,
 'must': 4285,
 'elstupido': 1,
 'filters': 22,
 'wait': 7997,
 'till': 4715,
 'puter': 54,
 'something': 7299,
 'else': 2880,
 'blame': 473,
 'broke': 3779,
 'seems': 3178,
 'longer': 1963,
 'terms': 141,
 'cold': 6369,
 'thecoolestout': 4,
 'ehhh': 75,
 'weathers': 160,
 'take': 8582,
 'turn': 1789,
 'chelserlynn': 1,
 'cooooold': 9,
 'incredible': 149,
 'stuff': 4528,
 'hoping': 2168,
 'rumbles': 8,
 'knights_': 1,
 'notice': 486,
 'told': 2550,
 'id': 4447,
 'agency': 57,
 'said': 5028,
 'bedtime': 302,
 'alive': 474,
 'yawwwnn': 1,
 'tired': 11622,
 'imma': 605,
 'try': 4356,
 'hopefully': 2504,
 'headstart': 5,
 'aghsnow': 1,
 'kenny': 71,
 'powers': 128,
 'bridgetsbeaches': 4,
 'thank': 2211,
 'letting': 580,
 'direct': 441,
 'message': 1102,
 'bridget': 25,
 'india': 290,
 '100th': 56,
 'test': 1985,
 'victory': 59,
 '10th': 144,
 'consecutive': 23,
 'win': 2682,
 'without': 5096,
 'guess': 6803,
 'ozesteph1992': 1,
 'stephan': 11,
 'mrsaintnick': 2,
 'leavin': 230,
 'intending': 6,
 'finish': 2127,
 'editing': 293,
 '536page': 1,
 'novel': 80,
 'manuscript': 8,
 'probably': 3606,
 'happen': 2120,
 '12': 2003,
 'pages': 455,
 'left': 8117,
 'laid': 256,
 'twista202': 3,
 'havent': 7149,
 'read': 3679,
 '9thamp10th': 1,
 'princess': 244,
 'diaries': 16,
 'saving': 245,
 'francesca': 7,
 'end': 4435,
 'easy': 1017,
 'books': 958,
 'nokia': 155,
 '1110': 7,
 'died': 3417,
 'mom': 4247,
 'breast': 70,
 'cancer': 567,
 'worried': 1450,
 'better': 10563,
 'rumblepurr': 7,
 'understood': 84,
 'daylight': 53,
 'savings': 61,
 'ended': 1068,
 'breakfast': 1573,
 'keep': 4917,
 'waking': 1242,
 'onemoreproject': 1,
 'lame': 1512,
 'understand': 1730,
 'heroes': 161,
 'isnt': 6983,
 'season': 2369,
 'living': 1072,
 'downtown': 347,
 'fun': 9857,
 'jonathanchard': 2,
 'calorie': 31,
 'wise': 136,
 'junk': 211,
 'food': 3816,
 'free': 2572,
 'ate': 2055,
 'sour': 150,
 'skittles': 59,
 'ass': 2246,
 'cherry': 164,
 'coke': 315,
 'man': 7382,
 'hard': 6093,
 'hot': 5908,
 'studying': 2318,
 'sleeeep': 55,
 'eyebrows': 73,
 'waxed': 20,
 'phantasy': 1,
 'star': 883,
 'macheist': 8,
 '30': 2844,
 'apps': 526,
 'sweet': 1533,
 'espresso': 59,
 'serial': 48,
 'although': 1036,
 'sent': 1398,
 'picked': 541,
 'mich': 32,
 'st': 564,
 'pretty': 4773,
 'pick': 1320,
 'way': 11626,
 'untiltonight': 2,
 'alone': 3856,
 'downstairsworking': 1,
 'ryanseacrest': 103,
 'anoop': 27,
 'mean': 4079,
 'seriously': 2684,
 'kinda': 3421,
 'pinkserendipity': 3,
 'sprint': 181,
 '4g': 9,
 'baltimore': 76,
 'chicago': 727,
 'far': 4164,
 'stuck': 4145,
 'awake': 2935,
 'middle': 920,
 'second': 1520,
 'row': 669,
 'felt': 1439,
 'bursting': 17,
 'bubble': 178,
 'gosh': 1078,
 'marieclr': 4,
 'naughtyhaughty': 3,
 'page': 1396,
 'sooooo': 1011,
 'until': 5862,
 'deleted': 671,
 'history': 1082,
 'crazy': 2746,
 'wind': 421,
 'birding': 2,
 'currently': 797,
 'grrr': 814,
 'ipods': 66,
 'acting': 544,
 'weird': 1801,
 'jai': 28,
 'ho': 247,
 'thinking': 3611,
 'arent': 2249,
 'full': 2586,
 'songs': 1100,
 'ughh': 767,
 'penndbad': 1,
 'dvd': 823,
 'cos': 1376,
 'heaps': 147,
 'deal': 886,
 'website': 1084,
 'machineplay': 1,
 'through': 3607,
 'therapyfail': 1,
 'colindemar': 1,
 'rail': 46,
 ...}

In [11]:
word_dict_positive

{'i': 288730,
 'love': 46839,
 'health4uandpets': 7,
 'u': 30160,
 'guys': 8173,
 'r': 3462,
 'the': 263836,
 'best': 11060,
 'im': 74853,
 'meeting': 1744,
 'up': 40069,
 'with': 64943,
 'one': 25823,
 'of': 90870,
 'my': 124977,
 'besties': 181,
 'tonight': 12005,
 'cant': 19006,
 'wait': 13863,
 'girl': 5723,
 'talk': 3701,
 'darealsunisakim': 4,
 'thanks': 33723,
 'for': 117013,
 'twitter': 18543,
 'add': 3517,
 'sunisa': 2,
 'got': 27769,
 'to': 251926,
 'meet': 3351,
 'you': 176004,
 'once': 3940,
 'at': 49207,
 'a': 196860,
 'hin': 9,
 'show': 8288,
 'here': 16818,
 'in': 99893,
 'dc': 403,
 'area': 573,
 'and': 147222,
 'were': 11737,
 'sweetheart': 307,
 'being': 5878,
 'sick': 1356,
 'can': 26858,
 'be': 54132,
 'really': 18329,
 'cheap': 468,
 'when': 16720,
 'it': 111868,
 'hurts': 437,
 'too': 27577,
 'much': 16764,
 'eat': 3488,
 'real': 3411,
 'food': 3527,
 'plus': 1180,
 'your': 44241,
 'friends': 7854,
 'make': 12399,
 'soup': 491,
 'lovesbrooklyn2': 3,
 'he': 12304,
 'has': 11956,
 'that': 68740,
 'effect': 258,
 'on': 83515,
 'everyone': 10008,
 'productoffear': 1,
 'tell': 5922,
 'him': 7956,
 'just': 61876,
 'burst': 59,
 'out': 37524,
 'laughing': 758,
 'loud': 510,
 'because': 4904,
 'making': 4288,
 'me': 69901,
 'come': 11962,
 'sulk': 9,
 'r_keith_hill': 3,
 'thans': 6,
 'response': 314,
 'ihad': 4,
 'already': 5330,
 'find': 4861,
 'this': 40897,
 'answer': 1154,
 'keepinupwkris': 20,
 'am': 21110,
 'so': 63962,
 'jealous': 1223,
 'hope': 18690,
 'had': 20110,
 'great': 24881,
 'time': 29336,
 'vegas': 895,
 'how': 21299,
 'did': 12145,
 'like': 37108,
 'acms': 1,
 'tommcfly': 2227,
 'ah': 2796,
 'congrats': 3237,
 'mr': 1445,
 'fletcher': 76,
 'finally': 7697,
 'joining': 281,
 'e4voip': 1,
 'responded': 74,
 'stupid': 1109,
 'cat': 1167,
 'is': 108402,
 'helping': 706,
 'type': 806,
 'forgive': 179,
 'errors': 40,
 'crazy': 2798,
 'day': 44363,
 'school': 7345,
 'there': 18246,
 '10': 2525,
 'hours': 4542,
 'straiiight': 1,
 'about': 24165,
 'watch': 8113,
 'hills': 659,
 'spencerpratt': 55,
 'told': 1938,
 'ha': 4360,
 'happy': 20118,
 'birthday': 7555,
 'jb': 534,
 'naughtyhaughty': 3,
 'forget': 1753,
 'two': 4828,
 'half': 2149,
 'men': 759,
 'nileyjileyluver': 1,
 'haha': 20774,
 'dont': 22010,
 'worry': 1719,
 'youll': 3118,
 'get': 36168,
 'hang': 1672,
 'soundwav2010': 1,
 'least': 3800,
 'wont': 3222,
 'only': 10274,
 'feeling': 4013,
 'lost': 1854,
 'may': 4269,
 'cause': 2454,
 'many': 4146,
 'later': 6216,
 'than': 7469,
 'usual': 681,
 'nights': 946,
 'addicting': 156,
 'lutheranlucciol': 2,
 'sure': 9159,
 'dm': 1228,
 'if': 24300,
 'post': 3276,
 'link': 2178,
 'video': 4129,
 'ltlolgtso': 1,
 'miss': 5601,
 'better': 12253,
 'permission': 79,
 'blessing': 176,
 'first': 9590,
 'added': 915,
 'tweetie': 323,
 'new': 26643,
 'iphone': 1977,
 'michellardi': 1,
 'know': 25274,
 'think': 19346,
 'its': 49483,
 'globe': 60,
 'yeah': 12104,
 'sana': 58,
 'gumaling': 1,
 'na': 899,
 'ko': 322,
 'para': 78,
 'alam': 22,
 'din': 240,
 'kung': 72,
 'makakasama': 1,
 'ako': 163,
 'nicolerichie': 111,
 'picture': 2470,
 'very': 13701,
 'sweet': 5453,
 'catching': 647,
 'emails': 440,
 'rss': 98,
 'random': 1166,
 'bacn': 3,
 'then': 18743,
 'cutting': 180,
 'early': 4382,
 '1130pm': 13,
 'have': 62040,
 'dinner': 4490,
 'lauraw': 1,
 'dancing': 969,
 'around': 4577,
 'room': 2603,
 'pjs': 181,
 'jamming': 124,
 'ipod': 1225,
 'getting': 10733,
 'dizzy': 45,
 'well': 24532,
 'asked': 937,
 'didnt': 6974,
 'place': 3372,
 'peeps': 913,
 'contest': 453,
 'but': 46196,
 'voting': 483,
 'anyways': 706,
 'going': 30647,
 'bed': 9460,
 'goodnight': 4145,
 'dreams': 1947,
 'littlelumen': 3,
 'walking': 897,
 'over': 9349,
 'put': 3969,
 'deposit': 31,
 'down': 6563,
 'tomorrow': 14243,
 'now': 39728,
 'followinq': 2,
 'dachesterfrench': 18,
 'shud': 181,
 'do': 30843,
 'tha': 514,
 'same': 4816,
 'lordpov': 1,
 'are': 43818,
 'meant': 1237,
 'back': 23458,
 'quottwittering': 2,
 'from': 28051,
 'toilet': 139,
 'cubicle': 28,
 'somewherequot': 2,
 'aw': 1432,
 'holding': 290,
 'puppy': 562,
 'hes': 4691,
 'not': 32846,
 'mine': 2892,
 'cutie': 299,
 'ijohn': 2,
 'kitteh': 21,
 'sleepin': 90,
 'crotch': 18,
 'which': 3364,
 'proves': 46,
 'she': 8866,
 'likes': 831,
 'more': 18810,
 'dramabeats': 18,
 'agreed': 434,
 'reaching': 70,
 'amritsar': 1,
 'an': 17527,
 'hour': 2641,
 'bus': 846,
 'should': 12914,
 'wagah': 1,
 'border': 60,
 'by': 12545,
 '2pm': 111,
 'albinla': 1,
 'was': 45080,
 'thinking': 3512,
 'let': 5847,
 'interview': 1124,
 'youre': 13877,
 'famous': 520,
 'super': 2698,
 'star': 1893,
 'spend': 1191,
 'family': 3995,
 'tired': 4022,
 'gonna': 10493,
 'effing': 142,
 'throat': 200,
 'hurting': 90,
 'ooooohh': 3,
 'craving': 304,
 'pina': 25,
 'coladabanana': 1,
 'slushie': 5,
 'deon': 20,
 'upload': 584,
 'di': 265,
 'indowebster': 1,
 'dong': 79,
 'banggggg': 1,
 'wisdomous': 1,
 'welcome': 6560,
 'glad': 8142,
 'enjoyed': 1478,
 'hawaii808shellz': 1,
 'hahaha': 4730,
 'omg': 4464,
 'we': 27316,
 'wer': 52,
 'both': 3214,
 'laughin': 35,
 'off': 17217,
 'd': 2860,
 'hook': 282,
 'cuz': 1678,
 'das': 87,
 'rolllryt': 1,
 'sheldawg': 1,
 'sickwiththepen': 2,
 'awww': 2053,
 'pookie': 16,
 'feel': 8208,
 'ill': 17597,
 'pray': 561,
 'youand': 26,
 'bag': 688,
 'nurse': 123,
 'yay': 10213,
 'found': 4040,
 'cuddle': 163,
 'buddy': 731,
 'met': 1461,
 'quotsnobquot': 1,
 'bad': 5405,
 'life': 7824,
 'goes': 1988,
 'across': 527,
 'universe': 323,
 'sleep': 9119,
 'rehearsal': 252,
 'annabellee': 1,
 'dry': 342,
 'potato': 198,
 'huh': 1032,
 'jonathanrknight': 838,
 'hi': 6874,
 'jon': 419,
 'hear': 4549,
 'see': 25460,
 'cruise': 304,
 'cannot': 861,
 'all': 39678,
 'knight': 281,
 'loved': 2925,
 'having': 7162,
 'long': 7424,
 'conversation': 436,
 'mom': 3621,
 'phone': 3965,
 'suitelifeofkell': 6,
 'yayyy': 322,
 'lol': 33470,
 'requested': 66,
 'herrr': 16,
 'what': 26532,
 'say': 9351,
 'practicing': 127,
 'linesmannerismsvoices': 1,
 'upcoming': 202,
 'feature': 285,
 'shoot': 872,
 'probably': 2846,
 'driving': 1252,
 'brock': 11,
 'go': 27785,
 'read': 4612,
 'moon': 1963,
 '3rd': 607,
 'enough': 2824,
 'twilight': 1483,
 'series': 754,
 'today': 28411,
 'our': 8092,
 'month': 1712,
 'anniversary': 536,
 'sooooooo': 121,
 'diana': 71,
 'even': 6661,
 'tar': 30,
 'heels': 217,
 'won': 2150,
 'ncaa': 11,
 'woot': 1061,
 'bored': 2217,
 'stevecla': 3,
 'wallpaper': 127,
 'red': 1973,
 'square': 229,
 'asking': 807,
 'pope_mello': 1,
 'noticed': 541,
 'bb': 609,
 'tryna': 150,
 'inspired': 365,
 'thats': 17469,
 'kourtneykardash': 55,
 'night': 22054,
 'workouts': 43,
 'ladygaga': 102,
 'ur': 8026,
 'hot': 4756,
 'ass': 1861,
 'austin': 265,
 'annnd': 23,
 'bob': 309,
 'purple': 418,
 'went': 5398,
 'royal': 114,
 'color': 561,
 'way': 12405,
 'as': 20672,
 'quotablebuffy': 4,
 'bunch': 715,
 'buffy': 86,
 'songs': 2247,
 'faves': 164,
 'quotvivianquot': 1,
 'nerf': 13,
 'herder': 2,
 'faith': 341,
 'spike': 49,
 'buffys': 3,
 'body': 834,
 'devunity': 1,
 'check': 6207,
 'gt': 1633,
 'morning': 19998,
 'tweetland': 16,
 'ahead': 1023,
 'uploading': 508,
 'pictures': 1770,
 'friendster': 83,
 'ash_ct': 3,
 'those': 5293,
 'days': 8507,
 'pic': 3570,
 'p': 2144,
 'noodlebox': 1,
 'amanda': 262,
 'una_avion2010': 3,
 'sorrry': 9,
 'doing': 8315,
 '29823782': 1,
 'different': 1308,
 'things': 5728,
 'kevin': 436,
 'jonas': 1786,
 'girlfriend': 474,
 'fuzeb': 1,
 'they': 14792,
 'serious': 638,
 'while': 5328,
 'singing': 1198,
 'whoa': 397,
 'hehe': 3796,
 'lsd': 3,
 'maybe': 6450,
 'jk': 862,
 'lolol': 158,
 'loving': 2565,
 'apothecaryjeri': 13,
 'sicilians': 2,
 'damn': 2261,
 'pizza': 1252,
 'planet': 271,
 'says': 2686,
 'loves': 2652,
 'chocolate': 1795,
 'milk': 605,
 'gf': 260,
 'sutter': 4,
 'creek': 90,
 'tour': 1635,
 'old': 5402,
 'bodycoach': 1,
 'look': 8051,
 'into': 5277,
 'cho': 44,
 'personally': 256,
 'strawberry': 410,
 'become': 696,
 'coach': 183,
 'soon': 9084,
 'little__fish': 1,
 'guess': 4370,
 'where': 5504,
 'live': 4935,
 'other': 5060,
 'side': 1553,
 'earth': 501,
 'east': 397,
 'mesa': 27,
 'losiento': 1,
 'paula_paige3489': 1,
 'apart': 328,
 'sore': 469,
 'tryouts': 26,
 'failed': 212,
 'physics': 154,
 'test': 1249,
 'homo': 48,
 'keeen': 1,
 'holidays': 391,
 '2': 16072,
 'observed': 9,
 'update': 1813,
 'alexa': 37,
 'website': 1409,
 'looks': 4965,
 'seems': 1852,
 'improving': 59,
 'leiabox': 2,
 'us': 7817,
 'totally': 3372,
 'geeking': 12,
 'right': 12487,
 'theragingocean': 2,
 'bonjour': 70,
 'spacecowboyi': 1,
 'wish': 5654,
 'either': 1772,
 'work': 18786,
 'kids': 2948,
 'whenever': 415,
 'want': 12338,
 'wherever': 131,
 'rebecca1158': 1,
 'brother': 1639,
 'quite': 2690,
 'weird': 1506,
 'drdrew': 14,
 'gives': 545,
 'hug': 830,
 'cookie': 329,
 'hey': 13670,
 'take': 8274,
 'care': 2293,
 'yourselfwe': 1,
 'rundown': 7,
 'hugs': 1330,
 'wrote': 733,
 'wall': 449,
 'correct': 353,
 'poor': 716,
 'spelling': 224,
 'highlighter': 7,
 'will': 29118,
 'wash': 412,
 'hardcore': 171,
 'good': 60846,
 'tech': 349,
 'clubzone': 2,
 'sushi': 654,
 'mattgalloway': 3,
 'carlyrush': 2,
 'suggesting': 41,
 'again': 12078,
 'bro': 1055,
 'rock': 2744,
 'jeffswarens': 5,
 'depends': 350,
 'version': 1000,
 'thought': 5016,
 'doesnt': 3150,
 'speak2ashley': 2,
 'hand': 1086,
 'still': 14042,
 'pretty': 7693,
 'weak': 129,
 'punch': 199,
 'anyone': 3128,
 'yet': 4532,
 'or': 16324,
 'turn': 1341,
 'knobs': 5,
 'hurt': 738,
 'honey3223': 14,
 'lurkers': 8,
 'interesting': 2311,
 'saravananp': 3,
 'b': 2086,
 'north': 465,
 'need': 13479,
 'decide': 418,
 'aaru': 1,
 'hithavaru': 1,
 'ninage': 1,
 'ee': 44,
 'moovarolage': 1,
 'vote': 1800,
 'trstfndbby': 1,
 'um': 603,
 'bought': 2565,
 'shit': 2004,
 'koreans': 13,
 'oach': 1,
 'highest': 68,
 'quality': 496,
 'baby': 4575,
 'paid': 614,
 'extra': 870,
 '350': 30,
 'tag': 274,
 'sewed': 6,
 'eating': 3846,
 'icecream': 277,
 'topping': 37,
 'iamdiddy': 304,
 'telling': 596,
 'finished': 4228,
 '200': 348,
 'crunches': 22,
 'step': 596,
 'diddy': 79,
 'lets': 4111,
 'its_yvonne': 1,
 'daaang': 3,
 'possible': 791,
 'whatd': 27,
 'lauruy': 1,
 'west': 544,
 'mostly': 516,
 'san': 618,
 'jose': 93,
 'francisco': 122,
 'nikki': 137,
 'working': 5869,
 'her': 13330,
 'bike': 980,
 'trying': 4316,
 'recover': 90,
 'knee': 160,
 'injury': 40,
 'marymayblood': 1,
 'would': 13058,
 'help': 5086,
 'unpack': 33,
 'sat': 1105,
 'afternoon': 2355,
 'shenagians': 1,
 'team': 1565,
 'awesomelt3': 1,
 'listening': 5525,
 'some': 26440,
 'music': 5655,
 'chillingill': 1,
 'regret': 155,
 'donebut': 4,
 'till': 3173,
 'kick': 798,
 'study': 1128,
 'amp': 22069,
 'grow': 402,
 'rich': 278,
 'wow': 6099,
 'amazing': 8816,
 'timeless': 23,
 'law': 405,
 'attraction': 53,
 '6': 1965,
 'program': 378,
 'bittenbybooks': 8,
 'oh': 16463,
 'ive': 9768,
 'been': 13305,
 'itll': 1243,
 'week': 9090,
 'though': 8957,
 '21': 470,
 'chris': 767,
 'comes': 1812,
 'home': 15391,
 '67': 38,
 'summer': 5327,
 'davidgideon': 5,
 'no': 21416,
 '147ish': 1,
 'therealjspace': 2,
 'tweet': 7096,
 'most': 4273,
 'drinking': 1640,
 'its_anne': 1,
 'kay': 226,
 'determined': 117,
 'baseball': 439,
 '5': 3376,
 'years': 2665,
 'since': 3498,
 'watched': 2729,
 'sport': 176,
 'interested': 703,
 'game': 4642,
 'beycah': 1,
 'becca': 80,
 'missnappyboy': 1,
 'ohhh': 503,
 'nkow': 1,
 'lexington': 20,
 'ky': 58,
 'rite': 265,
 'next': 9203,
 'seen': 2878,
 'preview': 259,
 'movie': 8229,
 'quotobsessedquot': 8,
 'w': 3479,
 'beyonce': 158,
 'broad': 38,
 'nuts': 250,
 'easy': 1665,
 'rider': 49,
 'fall': 1134,
 'asleep': 1161,
 'miketomalaris': 1,
 'excited': 7340,
 'broadcast': 88,
 'parisroubaix': 2,
 'moment': 1491,
 'missssssssss': 1,
 'belliestobabies': 1,
 'people': 9906,
 'survive': 192,
 'winter': 367,
 'without': 2059,
 'jungle': 88,
 'gyms': 9,
 'jaredleto': 54,
 'started': 2197,
 'last': 13080,
 'before': 5708,
 'holidayholiday': 1,
 'watchin': 988,
 'greek': 216,
 'knighty': 11,
 'media': 619,
 'design': 808,
 'client': 412,
 'profile': 992,
 'greeks05': 1,
 'lamehahaha': 1,
 'stalk': 153,
 'sexy': 1191,
 'lou911': 1,
 'aww': 2983,
 'another': 6241,
 'nitey': 41,
 'nite': 1845,
 'ahh': 1484,
 'kinda': 2371,
 'nervous': 448,
 'excitedtil': 1,
 'planning': 976,
 'whatever': 1103,
 'happier': 274,
 'heres': 831,
 'hopin': 40,
 'fb': 1502,
 'store': 1333,
 'missvic': 1,
 'mean': 3392,
 'jimmyeatworld': 10,
 'urbanthai': 1,
 'thank': 15398,
 'pamfr': 1,
 'pam': 70,
 'yes': 12289,
 'short': 1334,
 'struggle': 53,
 'choices': 125,
 'every': 3251,
 'hmm': 1435,
 'lot': 4847,
 'course': 3237,
 'late': 3322,
 'reading': 3246,
 'guykawasaki': 34,
 '100000': 100,
 'followers': 4874,
 'almost': 3554,
 '4': 7451,
 'times': 3840,
 'larrycarroll': 2,
 'any': 6059,
 'nm': 87,
 'updates': 1379,
 'screaming': 214,
 'wondering': 1060,
 'freakin': 430,
 'cooool': 61,
 'i3renda': 1,
 'theres': 3031,
 'nothing': 3941,
 'wrong': 1785,
 'caring': 127,
 'try': 6022,
 'why': 7157,
 'does': 4138,
 'brissa': 1,
 'lauren': 296,
 'jbrotherlove': 5,
 'story': 1773,
 'enbaldarlingg': 2,
 'mirror': 135,
 'looking': 7351,
 'amandahesser': 1,
 'couldnt': 1573,
 'done': 8283,
 'neat': 222,
 'god': 4696,
 'overitnowlt3': 1,
 'apologize': 103,
 'sharing': 885,
 'spiritual': 52,
 'general': 271,
 'public': 464,
 '31': 113,
 'until': 3441,
 'leave': 2298,
 'ontario': 69,
 'spoke': 179,
 'fam': 939,
 'japan': 260,
 'via': 1844,
 'skype': 316,
 'little': 8475,
 '16moold': 1,
 'nephew': 308,
 'growing': 335,
 'lissym': 2,
 'saw': 5293,
 'youd': 862,
 'written': 335,
 'someones': 233,
 'spoken': 81,
 'sucks': 955,
 'mcfly': 828,
 'loser': 255,
 'kacimaureen': 1,
 'holy': 574,
 'laundry': 559,
 'woman': 810,
 'hate': 2546,
 'trainer': 81,
 'markhoppus': 214,
 'youÃ¯Â½re': 43,
 'fucking': 1074,
 'funny': 5263,
 'setting': 359,
 'touch': 941,
 'officially': 1095,
 'nikhilnarayanan': 16,
 'tvc': 5,
 'yesterday': 3818,
 'worked': 1064,
 'could': 7919,
 'mannies': 1,
 'peddies': 1,
 'shut': 551,
 'fat': 592,
 'face': 2180,
 'magopus': 1,
 'ever': 6064,
 'run': 2460,
 'ideas': 745,
 'nominating': 3,
 'ones': 1727,
 'friend': 5575,
 'feels': 1704,
 'beer': 1483,
 'monday': 3555,
 'never': 6562,
 'always': 8193,
 'hopeinhell': 26,
 'usually': 851,
 'follows': 215,
 'special72': 1,
 'special': 1769,
 '72': 62,
 'luck': 5469,
 'rest': 2691,
 'cast': 275,
 'tbs': 78,
 'something': 6604,
 'leak': 37,
 'land': 619,
 'among': 135,
 'stars': 493,
 'johnhays': 4,
 'agree': 2071,
 'entirely': 113,
 'creative': 457,
 'vibrant': 17,
 'reasonbut': 4,
 'izzakizza': 1,
 'nada': 60,
 'holla': 264,
 'hows': 1879,
 'mixtape': 85,
 'coming': 5134,
 'aussie_ali': 22,
 'yep': 1898,
 'makes': 4331,
 'easier': 640,
 'points': 390,
 '140': 578,
 'snarkattack': 15,
 'freezerworthy': 1,
 'amoir': 13,
 'given': 456,
 'scholarly': 6,
 'attention': 486,
 'suppose': 537,
 'set': 1894,
 'eyes': 1283,
 'cupcakes': 370,
 'purrplexa': 1,
 'wonderful': 3146,
 'thing': 6885,
 'favor': 220,
 'using': 3120,
 'entire': 453,
 'english': 1421,
 'language': 355,
 'use': 4066,
 'expletives': 3,
 'mynameisgerard': 1,
 'saying': 1465,
 'walk': 1985,
 'flippin': 60,
 'cold': 1895,
 'outside': 2574,
 'ago': 2097,
 'sunny': 2509,
 'raining': 972,
 'snowing': 32,
 'sisterpatterson': 5,
 'ate': 1139,
 'raw': 168,
 'dough': 88,
 'tub': 148,
 'must': 4011,
 'kindred': 16,
 'spirits': 86,
 'internet': 1291,
 'dirty': 388,
 'song': 7147,
 'nighty': 360,
 'blooms5887': 1,
 'tweetdeck': 521,
 'facebook': 2289,
 'firestoned': 1,
 'dude': 2141,
 'awesome': 14127,
 'surprised': 546,
 'tweeting': 1689,
 'nsastrasasmita': 1,
 'k': 917,
 'figure': 1070,
 'llama': 18,
 'malcolm': 18,
 'meganltfuck': 1,
 'theatre': 210,
 'kayotae': 1,
 'martini': 60,
 'myself': 3883,
 'city': 1988,
 'soo': 2181,
 'spring': 483,
 'break': 1896,
 'watching': 14220,
 'moviess': 15,
 'everyday': 644,
 'pushplaynick': 9,
 'quotgrandpa': 1,
 'wants': 1944,
 'ice': 2140,
 'chest': 136,
 'beefquot': 4,
 'george': 312,
 'lopez': 50,
 'rulesss': 2,
 ...}

In [13]:
df_word_probs = pd.DataFrame({'Negative':pd.Series(word_dict_negative),'Positive':pd.Series(word_dict_positive)})
df_word_probs = df_word_probs.reset_index()
df_word_probs = df_word_probs.rename(columns={"index": "word"})
df_word_probs = df_word_probs.fillna(0)
df_word_probs['Total'] = df_word_probs['Negative'] + df_word_probs['Positive']
#df_word_probs.to_csv('word_counts_10.csv',index=False)
df_word_probs_10 = df_word_probs[df_word_probs['Total'] > 9]
df_word_probs_10

            word  Negative  Positive  Total
0              0     390.0     307.0  697.0
1             00      24.0      23.0   47.0
2            000      15.0      20.0   35.0
73           007       7.0       7.0   14.0
81      007peter       6.0       8.0   14.0
...          ...       ...       ...    ...
788005         Ã¹      23.0      64.0   87.0
788007        Ã¹Ã¸       3.0      11.0   14.0
788049       Ã¹Ã¸Ã¹       3.0       7.0   10.0
788068        Ã¹Ã¹       8.0      27.0   35.0
788085       Ã¹Ã¹Ã¹       2.0      13.0   15.0

[45380 rows x 4 columns]

In [14]:
common_words = df_word_probs_10['word'].to_list()

In [19]:
' ' in common_words

False

In [119]:
df_word_counts = pd.read_csv('word_counts.csv')
df_word_counts

#null take out

             word  Negative  Positive
0               0     390.0     307.0
1              00      24.0      23.0
2             000      15.0      20.0
3            0000       4.0       1.0
4           00000       0.0       1.0
...           ...       ...       ...
788105          Ã»       0.0       2.0
788106         Ã»Ã¸       0.0       1.0
788107  Ã»Ã¸Ã¹Ã¸Ã¸Â³Ã¸ÂªÃ¹       0.0       1.0
788108      Ã»ÃºÃ¸Ã¸Ã¹       0.0       1.0
788109        Ã»ÃºÃ¹       0.0       1.0

[788110 rows x 3 columns]

In [127]:
df_word_counts[df_word_counts['word']=='besties']

          word  Negative  Positive
85200  besties     136.0     181.0

In [20]:
pair_dict_negative = {}
pair_dict_positive = {}
bad_rows_counter = 0


for text_row in range(len(df['text'])) :
    list_of_words = re.sub(r'[^\w\s]', '', df['text'][text_row]).split()
    list_of_words_2 = []
    for word in list_of_words :
        word = word.lower()
        word = word.replace('?','')
        word = word.replace('!','')
        word = word.replace('.','')
        word = word.replace('"','')
        word = word.replace("'",'')
        word = word.replace('#','')
        word = word.replace('$','')
        word = word.replace(':','')

        if '@' not in word :
            list_of_words_2.append(word)

    for word_ind in range(len(list_of_words_2) - 1) :
        word_1 = list_of_words_2[word_ind]
        word_2 = list_of_words_2[word_ind + 1]
        
        if df['sentiment'][text_row] == 'Negative' :
            pair_dict_negative[(word_1,word_2)] = pair_dict_negative.get((word_1,word_2),0) + 1
            
        else :
            pair_dict_positive[(word_1,word_2)] = pair_dict_positive.get((word_1,word_2),0) + 1
#     except :
#         bad_rows_counter +=1
#         continue
print(bad_rows_counter)
pair_dict_positive

KeyboardInterrupt:

In [ ]:
df_bigrams = pd.DataFrame({'Negative':pd.Series(pair_dict_negative),'Positive':pd.Series(pair_dict_positive)})
df_bigrams = df_bigrams.reset_index()
df_bigrams = df_bigrams.rename(columns={"level_0": "word 1","level_1": "word 2"})
df_bigrams = df_bigrams.fillna(0)
df_bigrams['Total'] = df_bigrams['Negative'] + df_bigrams['Positive'] 
df_bigrams
# df_bigrams.to_csv('bigram_counts.csv',index=False)
# df_bigramsb

In [123]:
df_bigrams = pd.DataFrame({'Negative':pd.Series(pair_dict_negative),'Positive':pd.Series(pair_dict_positive)})
df_bigrams = df_bigrams.reset_index()
df_bigrams = df_bigrams.rename(columns={"level_0": "word 1","level_1": "word 2"})
df_bigrams = df_bigrams.fillna(0)
df_bigrams['Total'] = df_bigrams['Negative'] + df_bigrams['Positive'] 
df_bigrams
# df_bigrams.to_csv('bigram_counts.csv',index=False)
# df_bigramsb

            word 1    word 2  Negative  Positive  Total
0                0         0       6.0       1.0    7.0
1                0       0ki       0.0       1.0    1.0
2                0         1       2.0       0.0    2.0
3                0    13quot       0.0       1.0    1.0
4                0         2       2.0       1.0    3.0
...            ...       ...       ...       ...    ...
4542812          Ã»      Ã¸Â²Ã¹Ã¹       0.0       1.0    1.0
4542813         Ã»Ã¸        Ã¸Ã»       0.0       1.0    1.0
4542814  Ã»Ã¸Ã¹Ã¸Ã¸Â³Ã¸ÂªÃ¹     Ã¸Ã¸Ã¹Ã¸Ã¹       0.0       1.0    1.0
4542815      Ã»ÃºÃ¸Ã¸Ã¹         Ã¹       0.0       1.0    1.0
4542816        Ã»ÃºÃ¹  Ã¹Â¾Ã¸Ã¸Ã¸Â³Ã¸Ã¹       0.0       1.0    1.0

[4542817 rows x 5 columns]

In [124]:
df_bigrams.to_csv('bigram_counts.csv',index=False)

In [4]:
bigram_df_checl = pd.read_csv('bigram_counts.csv')
bigram_df_checl

            word 1    word 2  Negative  Positive  Total
0                0         0       6.0       1.0    7.0
1                0       0ki       0.0       1.0    1.0
2                0         1       2.0       0.0    2.0
3                0    13quot       0.0       1.0    1.0
4                0         2       2.0       1.0    3.0
...            ...       ...       ...       ...    ...
4542812          Ã»      Ã¸Â²Ã¹Ã¹       0.0       1.0    1.0
4542813         Ã»Ã¸        Ã¸Ã»       0.0       1.0    1.0
4542814  Ã»Ã¸Ã¹Ã¸Ã¸Â³Ã¸ÂªÃ¹     Ã¸Ã¸Ã¹Ã¸Ã¹       0.0       1.0    1.0
4542815      Ã»ÃºÃ¸Ã¸Ã¹         Ã¹       0.0       1.0    1.0
4542816        Ã»ÃºÃ¹  Ã¹Â¾Ã¸Ã¸Ã¸Â³Ã¸Ã¹       0.0       1.0    1.0

[4542817 rows x 5 columns]

In [26]:
bigram_small = bigram_df_checl[bigram_df_checl['Total'] > 9]

In [38]:
bigram_small['word_1_positive_total'] = bigram_small.apply(lambda row: 
                                    word_dict_positive.get(row['word 1'],0)
                                                           
                                                           , axis = 1)
bigram_small['word_1_negative_total'] = bigram_small.apply(lambda row: 
                                    word_dict_negative.get(row['word 1'],0)
                                                           
                                                           , axis = 1)
bigram_small['word_2_positive_total'] = bigram_small.apply(lambda row: 
                                    word_dict_positive.get(row['word 2'],0)
                                                           
                                                           , axis = 1)
bigram_small['word_2_negative_total'] = bigram_small.apply(lambda row: 
                                    word_dict_negative.get(row['word 2'],0)
                                                           
                                                           , axis = 1)
bigram_small

C:\Users\alxgs\AppData\Local\Temp/ipykernel_4848/2874588955.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bigram_small['word_1_positive_total'] = bigram_small.apply(lambda row:
C:\Users\alxgs\AppData\Local\Temp/ipykernel_4848/2874588955.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bigram_small['word_1_negative_total'] = bigram_small.apply(lambda row:
C:\Users\alxgs\AppData\Local\Temp/ipykernel_4848/2874588955.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bigram_small['word_2_positive_total'] = bigram_small.apply(lambda row:
C:\Users\alxgs\AppData\Local\Temp/ipykernel_4848/2874588955.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bigram_small['word_2_negative_total'] = bigram_small.apply(lambda row:

,word 1,word 2,Negative,Positive,Total,word_1_positive_total,word_1_negative_total,word_2_positive_total,word_2_negative_total
43,0,but,7.0,4.0,11.0,307,390,46196,81261
103,0,followers,6.0,4.0,10.0,307,390,4874,2264
109,0,for,16.0,4.0,20.0,307,390,117013,98679
146,0,i,11.0,7.0,18.0,307,390,288730,462019
1615,09,is,8.0,20.0,28.0,378,195,108402,127604
...,...,...,...,...,...,...,...,...,...
4537993,Ã°,Ã°Â½Ã°Âµ,2.0,12.0,14.0,245,55,102,30
4538074,Ã°,Ã±,7.0,15.0,22.0,245,55,211,50
4541058,Ã±,Ã°Â¼Ã°ÂµÃ°Â½Ã±,0.0,16.0,16.0,211,50,30,4
4541071,Ã±,Ã°Â½Ã°Ã±,2.0,9.0,11.0,211,50,17,4
4541091,Ã±,Ã°Â¾Ã±Ã±,3.0,10.0,13.0,211,50,11,3

In [41]:
bigram_small = bigram_small.rename(columns={"word 1": "word1", "word 2": "word2"})
bigram_small

,word1,word2,Negative,Positive,Total,word_1_positive_total,word_1_negative_total,word_2_positive_total,word_2_negative_total
43,0,but,7.0,4.0,11.0,307,390,46196,81261
103,0,followers,6.0,4.0,10.0,307,390,4874,2264
109,0,for,16.0,4.0,20.0,307,390,117013,98679
146,0,i,11.0,7.0,18.0,307,390,288730,462019
1615,09,is,8.0,20.0,28.0,378,195,108402,127604
...,...,...,...,...,...,...,...,...,...
4537993,Ã°,Ã°Â½Ã°Âµ,2.0,12.0,14.0,245,55,102,30
4538074,Ã°,Ã±,7.0,15.0,22.0,245,55,211,50
4541058,Ã±,Ã°Â¼Ã°ÂµÃ°Â½Ã±,0.0,16.0,16.0,211,50,30,4
4541071,Ã±,Ã°Â½Ã°Ã±,2.0,9.0,11.0,211,50,17,4
4541091,Ã±,Ã°Â¾Ã±Ã±,3.0,10.0,13.0,211,50,11,3

In [42]:
bigram_small.to_csv('bigram_small.csv',index=False)

In [43]:
df_small = pd.read_csv('bigram_small.csv')
df_small

,word1,word2,Negative,Positive,Total,word_1_positive_total,word_1_negative_total,word_2_positive_total,word_2_negative_total
0,0,but,7.0,4.0,11.0,307,390,46196,81261
1,0,followers,6.0,4.0,10.0,307,390,4874,2264
2,0,for,16.0,4.0,20.0,307,390,117013,98679
3,0,i,11.0,7.0,18.0,307,390,288730,462019
4,09,is,8.0,20.0,28.0,378,195,108402,127604
...,...,...,...,...,...,...,...,...,...
157597,Ã°,Ã°Â½Ã°Âµ,2.0,12.0,14.0,245,55,102,30
157598,Ã°,Ã±,7.0,15.0,22.0,245,55,211,50
157599,Ã±,Ã°Â¼Ã°ÂµÃ°Â½Ã±,0.0,16.0,16.0,211,50,30,4
157600,Ã±,Ã°Â½Ã°Ã±,2.0,9.0,11.0,211,50,17,4
157601,Ã±,Ã°Â¾Ã±Ã±,3.0,10.0,13.0,211,50,11,3

In [45]:
word_dict_positive['null']

5

In [31]:
bigram_small['word 1'].append(bigram_small['word 2'])

43               0
103              0
109              0
146              0
1615            09
            ...
4537993       Ã°Â½Ã°Âµ
4538074          Ã±
4541058    Ã°Â¼Ã°ÂµÃ°Â½Ã±
4541071       Ã°Â½Ã°Ã±
4541091       Ã°Â¾Ã±Ã±
Length: 315204, dtype: object

In [32]:
bigram_small['word 1']

43          0
103         0
109         0
146         0
1615       09
           ..
4537993     Ã°
4538074     Ã°
4541058     Ã±
4541071     Ã±
4541091     Ã±
Name: word 1, Length: 157602, dtype: object

In [34]:
#null take out from word count
len(set(bigram_small['word 1'].append(bigram_small['word 2'])))

14488